---
- name: Make Tenant ATX-Ansible1
  hosts: apics
  connection: local
  gather_facts: false


  vars_files:
    - external_vars.yml

  tasks:
    - name:  Creating Tenant
      cisco.aci.aci_tenant:
        tenant:  "{{  tenant_name  }}"
        description: "ATX-Ansible1 Tenant"
        host:  "{{ host }}"
        username: "{{ user }}"
        password: "{{ password }}"
        validate_certs: "{{ validate_certs  }}"
        state: absent




# Modified by Zalatan.
#
# Usage:  sudo ansible-playbook PB-DeleteTenantATX.yml -i SJC-Inventory-file  -vvv
#
#  docs.ansible.com is essential to make sure you got the modules right
# variables are defined in external_varsATX.yml
